# Generated by Django 3.2.2 on 2021-05-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='sub_title',
            new_name='header_subtitle',
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
