# Generated by Django 3.2.2 on 2021-05-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contactinfo_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='fullname',
            new_name='firstname',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_phone',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='current_website_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='lastname',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='organization',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
