# Generated by Django 3.2.2 on 2021-05-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20210513_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='header_color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
