# Generated by Django 3.2.2 on 2021-05-13 20:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_header_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=200)),
                ('header_description', ckeditor.fields.RichTextField()),
                ('header_img', models.ImageField(upload_to='features')),
                ('header_color', models.CharField(max_length=50)),
                ('body', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
