# Generated by Django 3.2.2 on 2021-05-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_featureitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='sub_title',
        ),
        migrations.AddField(
            model_name='feature',
            name='features_list_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='features_list_title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='header_subtitle',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='feature',
            name='header_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
