# Generated by Django 3.2.2 on 2021-05-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20210515_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banner'),
        ),
    ]
