# Generated by Django 3.2.2 on 2021-05-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20210508_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='slug',
            field=models.SlugField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
