# Generated by Django 3.2.2 on 2021-05-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolio_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='position',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='row',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
