# Generated by Django 3.2.2 on 2021-05-15 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_portfolio_column'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ('-id',)},
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='column',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='position',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='row',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='size',
        ),
    ]
